# What is Pytorch?

Pytorch is a power numerical library that is native to Python just like numpy and scipy. The one advantage it has over numpy is that it can operate over GPUs when asked for unlike numpy. Pytorch has been built primarily to implement deep neural networks over both CPUs and GPUs. Let us look some of the basic blocks of Pytorch.

### Torch Tensor.

In [1]:
import torch

In [2]:
x = torch.Tensor(3, 2)

In [3]:
print(x)


 1.3748e+37  1.9896e+31
 1.1520e-38  0.0000e+00
 2.5662e+30  9.9234e+21
[torch.FloatTensor of size 3x2]



As you can see that one can randomly initialize a torch tensor in this case a tensor of size 3 x 2. Of course such an initialization is not particularly useful specially when we want to initialize weights of a neural network for example. Just like numpy, torch also as access to many types of random number generators and we can in principle initialize the weights of an untrained neural network using such a scheme

In [4]:
weights =  torch.randn(5, 3)

In [5]:
print(weights)


-0.1925  0.3731 -1.0291
-0.0325  0.5206 -0.7136
-0.7641  2.5335 -1.3800
-0.2068  0.1668 -2.2258
-0.8391 -0.9635 -1.4378
[torch.FloatTensor of size 5x3]



The torch tensor weights have been initialized using the randn method that generates random numbers from a normal distribution. Let us initialize another torch tensor to play around with.

In [6]:
y = torch.rand(5, 3)

In [7]:
print(y)


 0.6304  0.0974  0.4601
 0.7145  0.9756  0.7628
 0.9100  0.1750  0.0988
 0.9744  0.6793  0.6484
 0.5958  0.6238  0.5687
[torch.FloatTensor of size 5x3]



In order to add two tensors we use torch.add method

In [8]:
z = torch.add(weights, y)

In [9]:
print(z)


 0.4379  0.4705 -0.5690
 0.6819  1.4962  0.0492
 0.1458  2.7085 -1.2811
 0.7676  0.8461 -1.5774
-0.2433 -0.3396 -0.8691
[torch.FloatTensor of size 5x3]



One can also add the tensor in place. For e.g.

In [10]:
y.__add__(weights)


 0.4379  0.4705 -0.5690
 0.6819  1.4962  0.0492
 0.1458  2.7085 -1.2811
 0.7676  0.8461 -1.5774
-0.2433 -0.3396 -0.8691
[torch.FloatTensor of size 5x3]

This another method to perform the addition operation. You use any operation in this and apply in this form to perform this operation. Let's us look at how to perform multiplication operations using tensors. 

In [11]:
torch.matmul(y, weights)

RuntimeError: size mismatch, m1: [5 x 3], m2: [5 x 3] at d:\pytorch\pytorch\torch\lib\th\generic/THTensorMath.c:1416

#### Why the error above?
As you can see there is a dimensional mismatch in the above scenario. We can fix this by transposing one of the tensors so that the multiplication operation is a valid one.

In [12]:
torch.matmul(y.t(), weights)


-1.5414  2.5010 -5.4397
-0.8481  0.4998 -3.4468
-0.8002  0.3794 -3.4150
[torch.FloatTensor of size 3x3]

We can use the method t() on the matrix in order to transpose a tensor. To know the size of the tensor use the size method.

In [13]:
y.size()

torch.Size([5, 3])

Similarly to numpy you can extract individual components or block of data from the tensor.

In [14]:
y[:, 1]


 0.0974
 0.9756
 0.1750
 0.6793
 0.6238
[torch.FloatTensor of size 5]

In [15]:
y[0,2]

0.460060715675354

In [16]:
y[3:, 1]


 0.6793
 0.6238
[torch.FloatTensor of size 2]

The result of such a tensor is also a tensor, but possibly of a different size. 

### Conversion from numpy to torch tensor and vice versa
Most of the real world data which you might be using will be most likely in the numpy format. This also means that the in order to use pytorch on this data you have to convert it into a torch tensor. This is very easy to do as we will demonstrate in the example below.

In [17]:
#Conversion from numpy array to tensor

In [18]:
import numpy as np

In [19]:
n_array = np.random.randn(5,4)

In [20]:
print(n_array)

[[-2.25482475 -1.05668625  0.50470798 -1.46718752]
 [-1.26139207 -1.10446727  0.47014498  0.04560771]
 [ 0.29193466 -0.40821379 -0.50282283  0.77099609]
 [-1.13177407  0.97220356  0.66009802 -1.38028801]
 [-1.9907153   0.68522901 -0.12355705  0.43001804]]


In [21]:
n_tensor = torch.from_numpy(n_array)

In [22]:
print(n_tensor)


-2.2548 -1.0567  0.5047 -1.4672
-1.2614 -1.1045  0.4701  0.0456
 0.2919 -0.4082 -0.5028  0.7710
-1.1318  0.9722  0.6601 -1.3803
-1.9907  0.6852 -0.1236  0.4300
[torch.DoubleTensor of size 5x4]



In [23]:
#Conversion from torch tensor to numpy array

In [24]:
new_array = n_tensor.numpy()

In [25]:
print(new_array)

[[-2.25482475 -1.05668625  0.50470798 -1.46718752]
 [-1.26139207 -1.10446727  0.47014498  0.04560771]
 [ 0.29193466 -0.40821379 -0.50282283  0.77099609]
 [-1.13177407  0.97220356  0.66009802 -1.38028801]
 [-1.9907153   0.68522901 -0.12355705  0.43001804]]


Thus it is very easy to switch between a torch tensor and numpy as well. In addition we can also move the computations to GPU using the cuda function:


In [26]:
torch.cuda.is_available()

True

In [27]:
if torch.cuda.is_available():
    n_tensor = n_tensor.cuda()

In [28]:
print(n_tensor)


-2.2548 -1.0567  0.5047 -1.4672
-1.2614 -1.1045  0.4701  0.0456
 0.2919 -0.4082 -0.5028  0.7710
-1.1318  0.9722  0.6601 -1.3803
-1.9907  0.6852 -0.1236  0.4300
[torch.cuda.DoubleTensor of size 5x4 (GPU 0)]



Let us perform some computations using some torch.cuda tensors

In [32]:
x = torch.randn(5, 5)
y = torch.rand(5, 5)

In [33]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()

In [34]:
torch.matmul(x, y)


-2.3299 -1.6405 -2.4680 -1.1606 -1.8798
 1.2381  1.1436  0.1950 -0.0786  1.1633
 3.4173  2.7793  2.9334  1.3266  2.6512
-1.1908 -1.2413 -0.4674 -0.2828 -0.2856
-2.3846 -2.3926 -2.6581 -0.7883 -2.8752
[torch.cuda.FloatTensor of size 5x5 (GPU 0)]

As you can see that it is very simple and straight forward to move the computations to the GPU. In the next tutorial we will look more into more faetures of Pytorch. We will learn enough features of pytorch so that we are able to implement a linear regressor at the start and then move towards more complex features.

#### Note: Pytorch supports CUDA computations only on graphic cards with compute capability > 3.0