# What is Pytorch?

Pytorch is a power numerical library that is native to Python just like numpy and scipy. The one advantage it has over numpy is that it can operate over GPUs when asked for unlike numpy. Pytorch has been built primarily to implement deep neural networks over both CPUs and GPUs. Let us look some of the basic blocks of Pytorch.

### Torch Tensor.

In [2]:
import torch

In [3]:
x = torch.Tensor(3, 2)

In [4]:
print(x)


 3.8828e+28  4.5709e-41
 9.8819e-38  0.0000e+00
 4.4842e-44  0.0000e+00
[torch.FloatTensor of size 3x2]



As you can see that one can randomly initialize a torch tensor in this case a tensor of size 3 x 2. Of course such an initialization is not particularly useful specially when we want to initialize weights of a neural network for example. Just like numpy, torch also as access to many types of random number generators and we can in principle initialize the weights of an untrained neural network using such a scheme

In [5]:
weights =  torch.randn(5, 3)

In [6]:
print(weights)


 0.3367  2.7201 -0.2530
-0.0366  0.5139 -0.6024
 2.3812  0.8604  0.7523
-0.5930 -0.9773 -0.5374
-1.0039 -0.9746 -0.6128
[torch.FloatTensor of size 5x3]



The torch tensor weights have been initialized using the randn method that generates random numbers from a normal distribution. Let us initialize another torch tensor to play around with.

In [7]:
y = torch.rand(5, 3)

In [8]:
print(y)


 0.1737  0.4563  0.8196
 0.7227  0.1825  0.7609
 0.3398  0.7620  0.4264
 0.2850  0.3265  0.8820
 0.9720  0.6519  0.5444
[torch.FloatTensor of size 5x3]



In order to add two tensors we use torch.add method

In [9]:
z = torch.add(weights, y)

In [10]:
print(z)


 0.5104  3.1764  0.5666
 0.6861  0.6963  0.1586
 2.7210  1.6224  1.1787
-0.3079 -0.6508  0.3445
-0.0319 -0.3227 -0.0683
[torch.FloatTensor of size 5x3]



One can also add the tensor in place. For e.g.

In [11]:
y.__add__(weights)


 0.5104  3.1764  0.5666
 0.6861  0.6963  0.1586
 2.7210  1.6224  1.1787
-0.3079 -0.6508  0.3445
-0.0319 -0.3227 -0.0683
[torch.FloatTensor of size 5x3]

This another method to perform the addition operation. You use any operation in this and apply in this form to perform this operation. Let's us look at how to perform multiplication operations using tensors. 

In [15]:
torch.matmul(y, weights)

RuntimeError: size mismatch, m1: [5 x 3], m2: [5 x 3] at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/TH/generic/THTensorMath.c:1416

As you can see there is a dimensional mismatch in the above scenario. We can fix this by transposing one of the tensors so that the multiplication operation is a valid one.

In [16]:
torch.matmul(y.t(), weights)


-0.3038 -0.0897 -0.9725
 1.1134  1.0362 -0.2270
 0.1939  1.5948 -1.1525
[torch.FloatTensor of size 3x3]

We can use the method t() on the matrix in order to transpose a tensor. To know the size of the tensor use the size method.

In [17]:
y.size()

torch.Size([5, 3])

Similarly to numpy you can extract individual components or block of data from the tensor.

In [18]:
y[:, 1]


 0.4563
 0.1825
 0.7620
 0.3265
 0.6519
[torch.FloatTensor of size 5]

In [20]:
y[0,2]

0.8196196556091309

In [21]:
y[3:, 1]


 0.3265
 0.6519
[torch.FloatTensor of size 2]

The result of such a tensor is also a tensor, but possibly of a different size. 

### Conversion from numpy to torch tensor and vice versa
Most of the real world data which you might be using will be most likely in the numpy format. This also means that the in order to use pytorch on this data you have to convert it into a torch tensor. This is very easy to do as we will demonstrate in the example below.

In [22]:
#Conversion from numpy array to tensor

In [23]:
import numpy as np

In [26]:
n_array = np.random.randn(5,4)

In [28]:
print(n_array)

[[-0.72872713  0.75137175  0.29772388 -2.49996509]
 [-0.31701894 -1.58982436  0.15033212 -0.47462809]
 [-0.0274026   1.5232194  -0.90496095 -0.31579689]
 [-1.26823896  1.04118619 -2.41385211 -0.79164406]
 [ 0.30840072 -0.8508777  -0.69646014 -0.59893965]]


In [29]:
n_tensor = torch.from_numpy(n_array)

In [30]:
print(n_tensor)


-0.7287  0.7514  0.2977 -2.5000
-0.3170 -1.5898  0.1503 -0.4746
-0.0274  1.5232 -0.9050 -0.3158
-1.2682  1.0412 -2.4139 -0.7916
 0.3084 -0.8509 -0.6965 -0.5989
[torch.DoubleTensor of size 5x4]

